export default function TermsPage() {
    return (
      <main style={{ minHeight: '100vh', background: '#fdf6e3', fontFamily: 'Georgia, serif', color: '#2c1a0e', padding: '60px 24px 100px' }}>
        <div style={{ maxWidth: 780, margin: '0 auto' }}>
  
          <div style={{ textAlign: 'center', marginBottom: 48 }}>
            <a href="/" style={{ textDecoration: 'none', fontFamily: "'Playfair Display', Georgia, serif", fontSize: 22, color: '#6B0F0F', letterSpacing: '0.05em' }}>
              SantasLetter.ai
            </a>
            <div style={{ height: 2, background: 'linear-gradient(90deg, transparent, #c8922a 30%, #d4aa5a 50%, #c8922a 70%, transparent)', margin: '16px 0 0' }} />
          </div>
  
          <h1 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 32, color: '#6B0F0F', fontWeight: 400, marginBottom: 8 }}>Terms of Service</h1>
          <p style={{ fontSize: 13, color: 'rgba(44,26,14,0.5)', marginBottom: 40, fontStyle: 'italic' }}>Last updated: April 17, 2026</p>
  
          <p style={{ fontSize: 15, lineHeight: 1.85, marginBottom: 24 }}>
            Welcome to SantasLetter.ai. By using our website and services, you agree to these Terms of Service. Please read them carefully. If you do not agree, do not use our service.
          </p>
  
          {[
            {
              title: '1. The Service',
              content: `SantasLetter.ai provides AI-generated personalised letters written in the style of Santa Claus for entertainment and family enjoyment purposes. Letters are fictional creative content and are not affiliated with, endorsed by, or connected to any official Santa Claus organisation, the United States Postal Service, or any other entity.
  
  We offer free letter previews, premium downloadable PDF letters, and physical letters mailed to your address.`
            },
            {
              title: '2. Eligibility',
              content: `You must be at least 18 years of age to use this service and make purchases. By using SantasLetter.ai, you confirm that you are an adult purchasing on behalf of a child in your care.`
            },
            {
              title: '3. Payments and Refunds',
              content: `All payments are processed securely through Stripe. Prices are listed in USD.
  
  Digital products (PDF letters): Due to the immediate delivery of digital goods, all sales of digital products are final and non-refundable once the PDF has been delivered to your email.
  
  Physical letters: If your physical letter does not arrive within 14 days of your expected delivery date, or arrives damaged, please contact us at privacy@santasletter.ai and we will arrange a reprint or refund at our discretion.
  
  If you experience a technical issue that prevents delivery of your digital product, contact us within 7 days and we will resolve it promptly.`
            },
            {
              title: '4. Delivery',
              content: `Physical letters are printed and mailed via USPS First Class Mail through our fulfilment partner Lob.com. Estimated delivery is 5–10 business days within the United States.
  
  International delivery times vary. We are not responsible for delays caused by postal services, customs, or circumstances beyond our control.
  
  For Christmas delivery, we strongly recommend ordering physical letters by December 15. We cannot guarantee Christmas delivery for orders placed after this date.`
            },
            {
              title: '5. Content and Acceptable Use',
              content: `You are responsible for the accuracy of the information you provide to generate a letter. Please do not include sensitive personal information beyond what is necessary (child's first name, age, and interests).
  
  You may not use SantasLetter.ai to generate content that is harmful, abusive, or inappropriate for children. We reserve the right to refuse service to anyone at our discretion.
  
  Generated letters are for personal, non-commercial use only. You may not resell, redistribute, or commercialise letters generated by our service.`
            },
            {
              title: '6. Intellectual Property',
              content: `The SantasLetter.ai website, brand, logo, and underlying technology are owned by us and protected by intellectual property laws.
  
  The personalised letter generated for your child is licensed to you for personal use. We retain the right to use anonymised letter content to improve our AI models.`
            },
            {
              title: '7. Disclaimer of Warranties',
              content: `SantasLetter.ai is provided "as is" without warranties of any kind, express or implied. We do not guarantee that the service will be uninterrupted, error-free, or that letters will meet your specific expectations.
  
  AI-generated content may occasionally contain errors or unexpected output. We review our systems regularly but cannot guarantee perfection in every generated letter.`
            },
            {
              title: '8. Limitation of Liability',
              content: `To the fullest extent permitted by law, SantasLetter.ai shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability to you for any claim shall not exceed the amount you paid us in the 30 days preceding the claim.`
            },
            {
              title: '9. Governing Law',
              content: `These Terms are governed by the laws of the State of California, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of California.`
            },
            {
              title: '10. Changes to These Terms',
              content: `We may update these Terms from time to time. Continued use of the service after changes are posted constitutes your acceptance of the new Terms. We will update the date at the top of this page when changes are made.`
            },
            {
              title: '11. Contact',
              content: `For any questions about these Terms, please contact us at:
  
  privacy@santasletter.ai
  
  SantasLetter.ai
  California, United States`
            },
          ].map(({ title, content }) => (
            <div key={title} style={{ marginBottom: 36 }}>
              <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 20, color: '#6B0F0F', fontWeight: 400, marginBottom: 12 }}>{title}</h2>
              <div style={{ height: 1, background: 'rgba(200,146,42,0.3)', marginBottom: 14 }} />
              {content.split('\n').map((line, i) => (
                <p key={i} style={{ fontSize: 14, lineHeight: 1.85, marginBottom: line.trim() === '' ? 8 : 6, color: '#2c1a0e' }}>{line}</p>
              ))}
            </div>
          ))}
  
          <div style={{ marginTop: 60, paddingTop: 24, borderTop: '1px solid rgba(200,146,42,0.3)', textAlign: 'center' }}>
            <a href="/privacy" style={{ color: '#6B0F0F', fontSize: 13, marginRight: 24, textDecoration: 'none' }}>Privacy Policy</a>
            <a href="/" style={{ color: '#6B0F0F', fontSize: 13, textDecoration: 'none' }}>← Back to SantasLetter.ai</a>
          </div>
  
        </div>
      </main>
    )
  }